### ISSUE TITLE
Add attributes to iframe

### ISSUE THREAD

**Issue by tneullas** [wanadev/obsidian-api#60]
We would like to be able to add attributes to iframe element that is created.
Use case is we want to be able to add a fullscreen button inside the iframe.

For security reasons, starting a year ago, browsers have limited iframe from going fullscreen without being explicitly authorized by main page (iframe parent).

For now `document.querySelector("#obsidian-app iframe").setAttribute("allow", "fullscreen");` would do the trick but it would be more convenient as a built in feature.

Thanks by advance !

**Comment by flozz** [comment]
Released in Obsidian API v2.1.0 :)

https://github.com/wanadev/obsidian-api/releases/tag/v2.1.0
